### ISSUE TITLE
'core' default password is not documented.

### ISSUE THREAD

**Issue by bartonski** [coreos/docs#10]
In docs/using-coreos/index.md the default user is shown to be `core`

> **NOTE**: the user for ssh is `core`.

When I try to log in via ssh, I am prompted for a password -- the default password is neither empty nor `core` -- the obvious choices. What is the default password?

**Comment by langdead** [comment]
My coreos was installed var vagrant last week, with kenel 3.17.8, the latest version so far.
`vagrant box add coreos http://stable.release.core-os.net/amd64-usr/current/coreos_production_vagrant.box`
I still get the problem that both system login and `vagrant ssh` need a password. 

Before the failure this time, I did succeed var `vagrant ssh` two days ago.

Now what can I do, please? Reinstall the coreos? Help is appreciated!

**Comment by robszumski** [comment]
@langdead Have you made any changes to the coreos-vagrant repo since you pulled it down?

**Comment by langdead** [comment]
@robszumski Thanks for contacting! If I remember correctly, no. I even didn't find where the repo locates in my disk. :(.
I just tried installing redmine during the last successful login.

To check what happens behind, I re-initiated the coreos by.
1 vagrant destroy
2 vagrant init coreos
3 changing the ip configuration and enable virtualbox gui in the file "Vagrant"
3 vagrant up

The first time it boots correctly, and vagrant ssh works.
Then either in ssh `shutdown -h 0` or `vagrant halt` from the host shell.

Now in host shell, `vagrant up` fails to login.

Thanks for your help in advance!

**Comment by robszumski** [comment]
> default: Vagrant insecure key detected. Vagrant will automatically replace
default: this with a newly generated keypair for better security.
default: 
default: Inserting generated public key within guest...
default: Removing insecure key from the guest if its present...
default: Key inserted! Disconnecting and reconnecting using new SSH key...

It seems like Vagrant has generated new keys for that CoreOS machine. I wasn't aware that this feature existed, I think it's new. If you set `config.ssh.insert_key = false`, that should disable the feature.

It seems like this is [already in coreos-vagrant](https://github.com/coreos/coreos-vagrant/blob/7dfbd0846d4ddc2d73e41271eb14b2e9938fac6c/Vagrantfile#L46), you might have an old copy on your machine.

**Comment by langdead** [comment]
@robszumski, thanks very much!
Adding config.ssh.insert_key = false fixed the issue! 

I meant to try coreos-vagrant, but the great GFW of China blocked... And, annoyingly, seemed that coreos-net is also blocked since this week...

Anyway, I can play with kernel 3.17.8 for some time... :)
