### ISSUE TITLE
etcd 2->3 migration docs for Container Linux

### ISSUE THREAD

**Issue by euank** [coreos/docs#1062]
We don't have a container-linux specific etcd migration guide for 2->3->3.1.

We probably should since it's a little involved!

Things worth pointing out:

The data directory between etcd2 and etcd-member changes from `/var/lib/etcd2` to `/var/lib/etcd`; the etcd2 data directory might have to be moved before some things work, and the backup instructions might need to take that into account.

The migration requires two steps: from 2->3.0 and from 3->3.1. those might require manual twiddling of the etcd-member image tag depending on your container linux version.

**Comment by euank** [comment]
cc @gyuho

**Comment by marcofranssen** [comment]
We are facing the same issues. In order to do the upgrade to kubernetes 1.6.x we first need to upgrade etcd to v3. However there is no clarity on how to do this exactly. Also the initial fresh cluster setup guide is still mentioning etcd v2, but the rest of the guide is using kubernetes 1.6. So it looks like some docs are still missing or not updated.

Basically step 3 is unclear for us. How do we `drop-in etcd 3`?

**Comment by gyuho** [comment]
This should be closed via https://github.com/coreos/etcd/pull/7956 and https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_0.md. No need to have separate 'upgrade' docs for Container Linux.

**Comment by marcofranssen** [comment]
@gyuho that is exactly the docs we are trying to follow. But we are not sure what exactly has to be done to replace etc2 with etc3 as there are no commands / detailed steps in this guide in [step 3](https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_0.md#3-drop-in-etcd-v30-binary-and-start-the-new-etcd-process). 

Would be great if you could help us out on some more detailed steps on the steps required to do the replacement. Or maybe you know of some documentation on how to replace this service properly.

How do I make sure etc3 is running also after system reboots? How do I uninstall etc2? How do I rollback in case of issues. Now I just snapshotted the VMs...

**Comment by gyuho** [comment]
> How do I uninstall etc2?

There is no need to uninstall etcd v2. Just stop the service.

And follow the migration guide https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_0.md on the v2 data.

If you have more questions, please open an issue in etcd github.

Thanks!
