### ISSUE TITLE
How do you actually get ct?

### ISSUE THREAD

**Issue by jimmycuadra** [coreos/docs#1068]
The [provisioning](https://coreos.com/os/docs/latest/provisioning.html) and [config transpiler overview](https://coreos.com/os/docs/latest/overview-of-ct.html) documents never explain how you actually get the `ct` application. Where is it downloaded from? Seems like this should be super obvious, but I can't find it anywhere.

**Comment by crawford** [comment]
Not sure how I missed that... :disappointed:

The binaries can be downloaded from [GitHub](https://github.com/coreos/container-linux-config-transpiler/releases). I'll go ahead and fix up the docs.

**Comment by sanmai-NL** [comment]
Indeed, very confusing! I do not see fixed up docs yet, but perhaps I missed something.

**Comment by crawford** [comment]
@sanmai-NL I haven't gotten around to it yet. As long as this issue is open, it will still be in our backlog. Pull requests, of course, are always welcome.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/docs/pull/1093.
