### ISSUE TITLE
Missing `coreos` key

### ISSUE THREAD

**Issue by sanmai-NL** [coreos/docs#1090]
Couldn't file an issue under that project, but [this overview](https://github.com/coreos/container-linux-config-transpiler/blob/37f030b89bccbb0edcbb9a9429bcb73cee47755c/doc/configuration.md) misses the `coreos` key.

**Comment by crawford** [comment]
To which key are you referring?

**Comment by bgilbert** [comment]
Container Linux Configs and cloud-configs are both YAML, but are otherwise substantially different.  CLCs don't have the `coreos` key.  See [this page](https://coreos.com/os/docs/latest/migrating-to-clcs.html) for more information on migrating to Container Linux Configs.
