### ISSUE TITLE
How you guys generate the HTML site off the Markdown documents? 

### ISSUE THREAD

**Issue by pavlo** [coreos/docs#1091]
It is not a bug nor feature request, it is rather a question, hope it is okay if I post it here...

Can you guys please describe the routine you perform in order to compile the final HTML pages generated off the Markdown documents in this repository? 

My objective is to create an infrastructure for documentation authoring and publishing for a project I am engaged in. I saw a bunch of tools such as `Jekyll` and `Hugo` but after playing with them for a bit found that they are not documentation-oriented so speak, they more are of blog/site which is not what I think I am looking for.

So I went to where I believed I saw really good documentation in terms of usability and quality - https://coreos.com/docs and decided to ask how you guys do it. Hope you don't mind to expose a little bit of internals that stay behind the documentation authoring/publishing process.

Thanks!

**Comment by joshix** [comment]
@pavlo We certainly appreciate the compliment on the docs. The process, however, is a little clunky. A new deployment without our peculiar concerns could probably do better than imitating it.

The site is generated from Markdown source (as you can see in the repos), eventually built into HTML by Jekyll. However, that's a simplification -- we do a lot of custom templating, rewriting, text processing, and link munging/checking to produce the final site output from an array of repos' `/Doc^(s umentation)/` directories. We go to great pains to make the docs legible both on our site in their official publication, and on GitHub (not to mention in terminals), so we have to transpose links between the two output targets. This is done by a custom and terribly site-specific synchronization program at each release for each project.

**Comment by robszumski** [comment]
I also wrote this up on https://github.com/coreos/docs/issues/1082

**Comment by euank** [comment]
Closing since I think this was answered
