### ISSUE TITLE
ssl_error_bad_cert_domain at first link in https://github.com/coreos/docs/blob/master/os/booting-on-cloudstack.md

### ISSUE THREAD

**Issue by RoestVrijStaal** [coreos/docs#1143]
But my bigger issue is that the tuto is too bare to figure out what to do at all. Everything is very vague and sparely documented. 

A better idea is to remove the tutorial and tell CloudStack uses are pretty much fucked and could better switch over to the better supported OpenStack or look at a different distro.

**Comment by bgilbert** [comment]
Hi @RoestVrijStaal!

It appears that our link is correct (see the [CloudStack main site](https://cloudstack.apache.org/), Documentation > Installation Docs) and the CloudStack docs site is misconfigured.  Questions about the TLS configuration of docs.cloudstack.apache.org should be directed to the CloudStack developers.

CloudStack is a [community-supported platform](https://coreos.com/os/docs/latest/#running-coreos) for Container Linux, so we rely on the user community to help keep its docs useful and up-to-date.  What in particular did you find confusing?

**Comment by RoestVrijStaal** [comment]
NVM it seems you can't run CoreOS on CloudStack when you're not owner of the CloudStack server.  Because in that case you can't supply the _user data_ for deploying & configuring CoreOS. 
You have to run all the stuff on your own.

**Comment by bgilbert** [comment]
Okay, if it turned out to be a permissions issue, I'll close.
