### ISSUE TITLE
kubelet-wrapper docs missing, but still necessary

### ISSUE THREAD

**Issue by euank** [coreos/docs#1161]
Container Linux ships the kubelet-wrapper script. Previously, this was documented as part of the old Kubernetes guide (at https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html).

That page now redirects to the new guide, which has no useful information on how to use kubelet-wrapper.

I assume it was a small oversight that this page got lost; regardless, for the OS we should provide rough documentation on how to run Kubernetes still.

The previous documentation was difficult to maintain because it tried to document all of Kubernetes.
If we instead just document the idiosyncrasies unique to our setup and recommendations, then we will have something easier to maintain and will still give the necessary information for a user to get going with K8s on Container Linux.

At a glance, it looks like we can copy the coreos-kubernetes kubelet-wrapper.md into our os docs and tweak it just a little.

**Comment by zbwright** [comment]
sounds like a plan to me. I'll make a Jira ticket to track this. @athai is currently building out the new landing page for Container Linux. Is this (rewritten) doc going to be high-profile enough that you would like to include it on the landing page under Reference? or should it live somewhere less prominent?

**Comment by zbwright** [comment]
Moved to https://jira.prod.coreos.systems/browse/DOCS-174. Close this issue, if you like, please.

**Comment by bgilbert** [comment]
The JIRA ticket isn't public, so let's leave this issue open until resolved.

**Comment by lucab** [comment]
Slightly related question for @euank: going forward, do we want to keep exposing&documenting kubelet-wrapper as a user interface (including all rkt args), or do we consider moving its ownership to tectonic and handle it as a k8s implementation detail (e.g. auto-updated by operators without user guarantees)?

**Comment by euank** [comment]
@lucab I personally think we should eventually recommend running the kubelet in a different way, including for tectonic.

Once we can recommend a different way (be it `--containerized` or a static binary on the host with something like `--experimental-gci-mounter` or a `PATH` with mount utilities from torcx), then we can remove documentation for the kubelet-wrapper.

I think we'll have to leave the kubelet-wrapper code on the disk for a long time even if we don't recommend or document it.

If tectonic wants to move to its own copy of kubelet-wrapper (e.g. in `/opt/kubelet-wrapper`) or move off it entirely sooner, that seems quite reasonable.

**Comment by euank** [comment]
Container Linux is deprecated. Closing this issue as stale.
