### ISSUE TITLE
Kubernetes and Tectonic

### ISSUE THREAD

**Issue by qrpike** [coreos/docs#1183]
I used the previous kubernetes install guide from CoreOS and its been working fine, but now when I go to the kubernetes docs on coreos.com it redirects to kubernetes+tectonic. Is there no longer a standalone kubernetes with coreos?

**Comment by bgilbert** [comment]
Hi @qrpike, those docs were unmaintained and out of date, and alternative resources are available. See [this coreos-user thread](https://groups.google.com/d/topic/coreos-user/LtmcOX_j4uM/discussion) for more details.
