### ISSUE TITLE
CoreOS Cluster with batch slurm managment

### ISSUE THREAD

**Issue by Seeyounes** [coreos/docs#1194]
Hi everyone,
Thanks a lot for your answer. I setup coreos cluster and i can see my coreos cluster with 3 nodes.  Now, i have to use batch slurm for test ? I don't where to start from ? could you please help ?

Thanks in advance.

**Comment by robszumski** [comment]
I saw your post on the mailing list, we can have the discussion there.

**Comment by Seeyounes** [comment]
Ok Rob Thanks a lot for your answer. I would be grateful. I can't figure out if i have to install something on CoreOS to support and use slurm ? I don't know  even if coreOS support slurm ? i'm using 3 coreos nodes as a cluster. What do you think ?
