### ISSUE TITLE
CoreOS Cluster with batch slurm managment

### ISSUE THREAD

**Issue by Seeyounes** [coreos/docs#1196]
Hi everyone,
Thanks a lot for your answer. I setup coreos cluster and i can see my coreos cluster with 3 nodes. Now, i have to use batch slurm for test ? I don't where to start from ? could you please help ?

Thanks in advance.

**Comment by lucab** [comment]
Hi! There is an open ML thread for this at https://groups.google.com/forum/#!topic/coreos-user/GJUXG8u6xqU. I don't have any specific insights into it, and it looks like nobody else has so far.

However, this tracker is not a place widely used for community discussions so I'd avoid duplicating such topic here.
