### ISSUE TITLE
Image verification links wrong

### ISSUE THREAD

**Issue by lewismarshall** [coreos/docs#1228]
The links to [CoreOS Image Signing Key - https://coreos.com/security/image-signing-key](https://coreos.com/security/image-signing-key) in [os/verify-images.md](https://github.com/coreos/docs/blob/master/os/verify-images.md) page are getting a 404:
 #

**Comment by bgilbert** [comment]
Whoops, those resources should not have been removed.  We'll get them restored today.  Thanks for the report!

**Comment by bgilbert** [comment]
This is fixed now.  Thanks again for reporting.
