### ISSUE TITLE
build_package error solution

### ISSUE THREAD

**Issue by Bubblemelon** [coreos/docs#1239]
Perhaps it would be useful to have this command:

`emerge-amd64-usr bash readline ncurses`

handy in the doc so that users going through the `sdk-modifying-coreos` page can continue to run `./build_packages` again (if build package errors occurs) and then to building the image.

**Comment by Bubblemelon** [comment]
For example: 

![screenshot from 2018-05-22 09-58-41](https://user-images.githubusercontent.com/12985181/40394687-5028177c-5dd9-11e8-81da-d31f5689b244.png)

**Comment by bgilbert** [comment]
This workaround will no longer be necessary after we switch to the upcoming SDK release.  We generally don't include short-term workarounds in our docs; they're available in the bug tracker for users who need them.

**Comment by Bubblemelon** [comment]
@bgilbert Yup that's right. 

I know get that this was case specific, where by doing `emerge-amd64-usr bash readline ncurses`  means that `emerge-amd64-usr` will rebuild `bash`, `readline` and `ncurses`. I was also told that David identified what to rebuild in this case.
