### ISSUE TITLE
Driver support for usb ethernet adapter 

### ISSUE THREAD

**Issue by joelmo** [coreos/docs#175]
I have no ethernet port on my machine so I need to use a usb-ethernet adapter. I'm using one from Apple and this is working with the asix usb driver, this driver also supports other  adapters. I can see from the log that ASIX AX88772 is loaded.

**Comment by robszumski** [comment]
Bump. cc: @marineam @crawford

**Comment by Dm3Ch** [comment]
@joelmo I've got same issue with other USB NIC. Have you found how to fix this issue?

**Comment by joelmo** [comment]
@Dm3Ch No I switched to NixOS.

**Comment by crawford** [comment]
@Dm3Ch can you file a bug at https://github.com/coreos/bugs/issues? The output of `lspci -nnk` would be helpful.

**Comment by Dm3Ch** [comment]
Ok, i'll do this. But i suppose that it is not a bug, it is too minimalistic kernel modules list. :)

**Comment by Dm3Ch** [comment]
@crawford I filed this issue as you requested. https://github.com/coreos/bugs/issues/1637
