### ISSUE TITLE
Can't find, how to change the default keyboard layout

### ISSUE THREAD

**Issue by pmario** [coreos/docs#237]
Hi folks, 
I'm new to coreos and can't find a way to change the default keyboard layout. Google search doesn't find anything either.

**Comment by jpcweb** [comment]
That's right it doesn't work!

I use the localectl command and it prints:
System Locale: n/a
VC Keymap: fr
X11 Layout: fr
X11 Model: pc105
X11 Options: terminate:ctrl_alt_bksp

I must run my coreOS 557.0.0 on virtualBox with $vm_gui=true because there is a connection timeout via vagrant

**Comment by vezq** [comment]
Does not work here either. Ended my CoreOS trial in short as I can't type some characters like = with sv keyboard.

**Comment by crawford** [comment]
As was mentioned above, we don't ship most locales in CoreOS. Your best bet is to SSH into the machine and allow your host terminal to handle locales.

**Comment by pedro93** [comment]
I also come across this problem. Is there no way to add keymaps without having access to external terminals? Not all keyboards have the US layout which makes working on container linux extremely hard. 
A guideline into how to add other country's keymaps would be incredibly useful.

**Comment by bgilbert** [comment]
Independently of whether we want to ship locales, we should start shipping keymap data.  It doesn't require much space, and folks with non-US keyboards might plausibly want to type at the console.

**Comment by bgilbert** [comment]
The OS change actually belongs in coreos/bugs, not here, so I've opened https://github.com/coreos/bugs/issues/2116.

We should have better documentation too, so I'll leave this open.

**Comment by pedro93** [comment]
So that no unecessary bytes are bundled in the container image, why not make a guide on how to add custom keyboard layout?
Give the user to ability to opt-in to that. I do not know what that would entail, it's merely a suggestion.

**Comment by bgilbert** [comment]
@pedro93 Thanks for the suggestion.  We currently ship neither the layouts nor the tools required to activate them, so the image will need changes in any case.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
