### ISSUE TITLE
Docs do not mention ARM

### ISSUE THREAD

**Issue by nathansamson** [coreos/docs#297]
I was looking for a way to deploy CoreOS on Bare Metal ARM devices (no not the rasperry Pi, that probably wouldn't work :), although it might (http://resin.io/blog/docker-on-raspberry-pi/)

I could not find anywhere in the docs how to download (or build) an ARM image.

Even if this is not supported (or even known to not work), a relevant warning / link to issue might be helpful.

Thanks :)

**Comment by iarenzana** [comment]
+1 on ARM. Actually, I think coreOS would be a great fit for the Pi. With light resource usage and clustering potential, it could make for a nifty testing lab.

**Comment by elecnix** [comment]
FYI: resin.io has launched for the Raspberry Pi.

**Comment by tdicola** [comment]
+1 on ARM support here too.  The new Raspberry Pi 2 is an ARMv7 architecture, so it's still a ways off from supporting 64-bit, virtualization, etc. but at least not the oddity of ARMv6 + FPU of the 1st gen Pi.

If it matters stuff like snappy Ubuntu Core support the Pi 2 (and other ARM platforms like BeagleBone Black) too: https://insights.ubuntu.com/2015/02/02/snappy-ubuntu-core-on-raspberry-pi-2/

**Comment by qerub** [comment]
> @tdicola: The new Raspberry Pi 2 is an ARMv7 architecture, so it's still a ways off supporting […] virtualization […]

Actually, the Raspberry Pi 2's Cortex-A7 has support for virtualization. (Sources: http://www.arm.com/products/processors/cortex-a/cortex-a7.php, http://wiki.xenproject.org/wiki/Xen_ARM_with_Virtualization_Extensions)

**Comment by nicksahler** [comment]
+1 on ARM for Pi 2 supporting virtualization :smile:

**Comment by mcanthony** [comment]
1+1 for the pi - dusting my compiler off as we type so I can join in the festivities

**Comment by djmaze** [comment]
Sorry, I don't get why the machine needs virtualization support. I think this was a misunderstanding of GKH's mailing list post. Docker, as used by CoreOS, does not depend on CPU virtualization features. People have Docker running even on the Pi 1. And I don't think CoreOS needs virtualization support either.

It should be possible to (cross-)compile all the system-level tools (including docker, etcd & fleet) for 32-bit armhf. I believe the main problem is in boot loader, firmware and kernel support. Most of the armhf-based devices use Uboot and special firmware. I am not sure this can be easily made compatible with the CoreOS way of booting (which AFAIK uses grub). Also there might be differences in which kernel options or device drivers might be required. And the GPT partitioning scheme in use by CoreOS might not work on those devices.

So this means, for every new ARM device, there needs to be a special configuration and, best, a corresponding suite of automated tests (which might not run correctly inside an emulator).
 
That said, I would be very happy to see ARM support ;) Maybe start with popular devices, e.g. Pi 2, Odroid-C1. Possibly, with some hints, the community could take over this work.

**Comment by robszumski** [comment]
I'm sure most of you saw this, but check out ["CoreOS on ARM64"](https://coreos.com/blog/coreos-on-arm64/) blog post if you haven't already.

**Comment by duffqiu** [comment]
+1 on ARM for Pi 2

**Comment by byrnedo** [comment]
!+1 for ARM on Pi 2

**Comment by marineam** [comment]
An arm64 port is in progress and should become usable soon. We do not plan on porting CoreOS to any 32bit arm architectures but would happily support and accept contributions for such a port. Given some of the cross-comiling issues will already be resolved for the 64bit port a 32bit port should be less difficult but still isn't trivial.

Closing, if an arm port ever materializes it will certainly be mentioned in the docs. :)

**Comment by Serkan-devel** [comment]
+1 for ARM on Pi 2
