### ISSUE TITLE
VMWare Insecure Image SSH not working

### ISSUE THREAD

**Issue by itguy51** [coreos/docs#303]
When I try to SSH into the "coreos_production_vmware_insecure" image with `ssh -i insecure_ssh_key core@192.168.64.135` I get the response `ssh_exchange_identification: read: Connection reset by peer`

Does this have to do with the fact that I am running CoreOS under NAT instead of Bridged? (My network doesn't have a DHCP server so CoreOS just sits there, ip-less under bridged) 

Also (Not really an issue, probably just me being incompetent with YAML), for the life of me I cannot get the config file working with my SSH keys. I've tried everything and it will not let me log in. Should the RSA key include the `user@hostname` at the end? basically the entire contents of `id_rsa.pub` should be there?

**Comment by robszumski** [comment]
These fixes should have made it through to all channels. Proper VMware support is also in progress: http://blogs.vmware.com/vsphere/2015/01/technical-preview-coreos-vsphere-5-5.html
