### ISSUE TITLE
I can't install CoreOS to disk

### ISSUE THREAD

**Issue by kikicarbonell** [coreos/docs#323]
I'm trying to install CoreOS to disk, and I'm following the recomendation from [official doc][1].
I have PXE with CoreOS, then I'm booting CoreOS from RAM and I continue these steps:

1- execute: `cfdisk -z /dev/sda`
2- execute: `touch "/usr.squashfs (deleted)"     # work around a bug in mkfs.btrfs 3.12`
3- execute: `mkfs.btrfs -L ROOT /dev/sda1`
1- copy all resources to /home/core (coreos-install and my-cloud-config.yml)
2- execute: `chmod +x coreos install`
3- execute: `sudo ./coreos-install -d /dev/sda -c /home/core/my-cloud-config.yml`

The output was:
```
...
Installing cloud-config...
[2312.930275] BTRFS info (device sda1): disk space caching is enabled
mount: mount(2) failed: No such file or directory
```

I don't know what's the problem, because on internet I can't find any report of this behavior during the installation of CoreOS. 

Any ideas, @robszumski, @brianredbeard, @philips, @vCarly ?

[1]: https://coreos.com/docs/running-coreos/bare-metal/installing-to-disk/

**Comment by robszumski** [comment]
CoreOS has officially moved to overlayfs: https://coreos.com/releases/#561.0.0
