### ISSUE TITLE
Vultr image does not existing

### ISSUE THREAD

**Issue by ghost** [coreos/docs#331]
Hello,

I'm trying to execute this:
```
sudo coreos-install -d /dev/vda -C stable
```

But I get 
```
/bin/coreos-install: Image URL unavailable: http://stable.release.core-os.net/amd64-usr/410.0.0/coreos_production_vultr_image.bin.bz2
```

How I can fix it ? Thank you.

**Comment by robszumski** [comment]
Please reopen if you're still having an issue with the install script.

**Comment by cosmoras** [comment]
Hello, i do have an issue, trying to install to HD from image at VULTR using he last command  from user marineam, I am getting this error a while after starting installation . Actualy the last succesfull report is :
gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" [ultimate]

and then errors 

/bin/coreos-install: line 249: /sbin/blockdev: Input/output error
/bin/coreos-install: line 1: /bin/rm: Input/output error

Please Help
