### ISSUE TITLE
coreos-install do not work (network problem)

### ISSUE THREAD

**Issue by suquant** [coreos/docs#335]
When trying to connect alpha.release.core-os.net on IPV6 address and downloading release packages, server returning forbidden status.

Please resolve this problem, thank you.

Log:
```bash
./coreos-install -d /dev/sda -C alpha -c config.yaml
> ./coreos-install: Image URL unavailable: http://alpha.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2
```

**Comment by robszumski** [comment]
Please reopen if this issue continues.
