### ISSUE TITLE
Writable root and first-time boot

### ISSUE THREAD

**Issue by hippich** [coreos/docs#337]
I would like to boot of PXE server to make sure I am using up-to-date CoreOS version and IP addresses are all correct, but I also want to have writable root. I could manually boot machine first, partition disk and then make it boot of PXE server, but this require manual intervention. In the same time if I specify anything for root= kernel option and my harddrive is not partitioned yet - coreos boot process stops. 

is there any approach which might allow me to boot first time without disk partitioned already but still to pick up partition on following boot if partition available? I read somewhere about STATE partition but it seems like this either not supported (yet/already?) or I was doing something wrong.

What I wound to get in the result - machine which will self-provision and join cluster as long as it is booted of PXE server with CoreOS image. Any ideas?

**Comment by philips** [comment]
I think this is now fixed. CoreOS has a writeable root.
