### ISSUE TITLE
Vultr documentation for cloud-config-url

### ISSUE THREAD

**Issue by tadas-subonis** [coreos/docs#341]
Hi,

it is not clear when and how should be "cloud-config-url" set. Could anyone expand on that? For example, what address should I provide? what it should point to exactly? what would be an example of output? what would change if the option is left invalid?

Thanks

**Comment by ryneeverett** [comment]
I submitted a ticket to vultr about this recently and it seems they still don't have cloud-config support in the control panel. The simplest way for me is to put my cloud-init in a gist and replace the `cloud-config-url` with the "raw" file url.

**Comment by ryneeverett** [comment]
That said, no matter what I do the partitioning comes out wrong, with the root partition only receiving 373mb, making the whole endeavor worthless so far.

**Comment by ryneeverett** [comment]
Oh I see, those instructions are for installing to RAM. [This blog post](http://blog.turret.io/launch-coreos-instances-with-pixe-and-cloud-config/) explains how to install to disk.
