### ISSUE TITLE
systemd: explain unit drop-ins

### ISSUE THREAD

**Issue by philips** [coreos/docs#364]
The systemd docs aren't very explicit so we should try to explain in our docs: http://www.freedesktop.org/software/systemd/man/systemd.unit.html

**Comment by ForbiddenEra** [comment]
+1 on this - would be helpful if there were more CoreOS specific documents on using systemd (while i'ts not specific, some things, like fleet unit files, are)

Whenever I Google something regarding it, I generally end up at an ArchLinux page.. ;-)

**Comment by robszumski** [comment]
Upstream systemd docs for reference: http://www.freedesktop.org/software/systemd/man/systemd.unit.html#Description

**Comment by robszumski** [comment]
https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html
