### ISSUE TITLE
beta release 522.2.0 broke cloud-config 

### ISSUE THREAD

**Issue by xueshanf** [coreos/docs#410]
I have cloud-config works on beta release up to 494.4.0 until the cluster was upgraded to beta 522.2.0. It took hours to figure out why some units were not installed by cloud-init and why fleet won't start. 

I think the the issue is with multiple coreos: and units: keys in cloud-config yaml file. Only the last Coreos: or units: are valid in 522.2.0, while in previous releases, multiple coreos: and units: were merged. I had using fragments of files  so some of the configurations can be shared, some are unique to a particular services.  Redo the cloud-config files to make sure keys are unique fixed the problem. 

Does anyone run into same issues? I did not see any mentioning in release notes.

**Comment by robszumski** [comment]
Is this considered closed?

**Comment by xueshanf** [comment]
@robszumski 

Just a suggestion - probably in the following documentation:

https://coreos.com/docs/cluster-management/setup/cloudinit-cloud-config/

mention that the cloud-config keys should be unique after this sentence:

"A cloud-config file must contain #cloud-config, followed by an associative array which has zero or more of the following keys: ...."

The examples in the same  documentation gives an impression that multiple "coreos:" key can be used and it  did worked in past releases until a recent change that cause things broken. 

That's just a thought. 

Yes please close the issue. Thanks!

**Comment by robszumski** [comment]
Thanks @xueshanf, we're still trying to find the best way forward with repeated sections.
