### ISSUE TITLE
Get notification about an update

### ISSUE THREAD

**Issue by metakeule** [coreos/docs#421]
When using CoreOS on a single host (I know, this is not the common use case) I want to prevent automatic reboots  after an update, so I would like to choose update strategy `off`. 

Instead, I want to check if there had been any updates once a day and if there are, reboot after making sure all pending operations of my docker apps did finish, there are no pending requests, the filesystem is synced etc.

In order to write such a script I need a way to figure out, if updates happened. I am sure there must be some way (via etcd). 

Please also add the recommended way to the [documentation for update strategies](https://coreos.com/docs/cluster-management/setup/update-strategies/).

Thanks for your great product!

**Comment by robszumski** [comment]
Did you see this part of that doc?

https://coreos.com/docs/cluster-management/setup/update-strategies/#auto-updates-with-a-maintenance-window

Is there not enough information there to base your script off that? What info can we add?

**Comment by metakeule** [comment]
@robszumski overlooked it, ok thanks, that's enough.

**Comment by xueshanf** [comment]
@robszumski 
With the auto-updates-with-a-maintenance-window example, all machines in a cluster would reboot all at once, e.g. 5am, if reboot is due, isn't?  That will cause a service outage. Randomly staggered reboot would be better.  Something like - reboot after waiting between 0 and 3600 seconds:

ExecStart=/usr/bin/bash -c 'if update_engine_client -status | grep NEED_REBOOT; then sleep t=$(expr $RANDOM % 3600); echo "Reboot in $t sec."; sleep $t; reboot; fi'

**Comment by robszumski** [comment]
@xueshanf `locksmithctl` takes a cluster-wide lock using etcd, to prevent exactly that. You can test this out by running `locksmithctl lock` on one machine and then running `locksmithctl reboot` on the other. You'll get this:

```
$ lockmsithctl lock
$ locksmithctl status
Available: 0
Max: 1

MACHINE ID
26c393f16f8e4f828ef3585e0cbd7ada
```

```
$ sudo locksmithctl reboot
Error locking: semaphore is at 0
```

Your example doesn't solve the problem, it just reduces the likelihood that you'll see ill effects.

<hr>

You did trigger a thought though...if that example timer only runs once at X time and it can't get the lock, it will have to wait until the next day at X. The example should be updated to have it run Y times from X to X+30. If you happen to play around with that, a PR would be much appreciated. If not, I'll add it to the backlog.
