### ISSUE TITLE
Conflicts between DHCP and static IP configuration via cloud-config

### ISSUE THREAD

**Issue by Nirkus** [coreos/docs#435]
Hey,

we have an issue with IP addresses being droped by coreos instances when they have the same IP address configured within DHCP and statically via /usr/share/oem/cloud-config.

It seems when the DHCP server leases the same IP address to a coreos interface as is configured statically via /usr/share/oem/cloud-config.yml, the IP address flag dynamic is not removed by coreos/systemd/systemd-networkd. So, the IP address is droped once the lease is expired (in this case 120 seconds) while it is supposed to be configured statically.

The cofiguration of the DHCP server has been carried out dynamically by some infrastructure management tool and this situation will probsbly standard in many infrastrutures.

coreos release is 522.6.0.

**Comment by Nirkus** [comment]
May be related to issue #377

**Comment by crawford** [comment]
This is indeed related to #377 (which was resolved). Give the latest stable (currently 557.2.0) a shot.

**Comment by philips** [comment]
Closing as this should be fixed.
