### ISSUE TITLE
Systemd getting started fails

### ISSUE THREAD

**Issue by lethjakman** [coreos/docs#439]
Hey,

I've noticed that if you follow the "Getting Started with systemd" tutorial your docker container will fail to start every time. It seems that the "docker pull busybox" is happening too quickly and returning an error like this:

Feb 22 22:48:20 general docker[628]: time="2015-02-22T22:48:20Z" level="fatal" msg="Get https://index.docker.io/v1/repositories/library/busybox/images: dial tcp: lookup index.docker.io: connection refused"

I have no clue what to do to fix this. I've tried things like "After=network-online.target" but nothing seems to allow a pull. Any ideas what this should really look like? Thank you.

**Comment by robszumski** [comment]
Moved this issue to bugs.

**Comment by lethjakman** [comment]
Oh. Thank you. I didn't realize that was an option.
