### ISSUE TITLE
EC2 User Data Requirements

### ISSUE THREAD

**Issue by hapnermw** [coreos/docs#451]
The instructions for cloud-config need to note that the AWS code in CoreOS AMIs that loads EC2 User Data requires that the first line be either exactly "cloud-config" if it is a config file or start with a shebang "#!" if it is a command.

This EC2 required first line yaml comment is not required for cloud-config files in general.

**Comment by jedsmith** [comment]
We already document this, as do Amazon. Is there something missing here?

- https://coreos.com/docs/cluster-management/setup/cloudinit-cloud-config/#file-format
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-shell-scripts

**Comment by hapnermw** [comment]
You are correct that it is documented.

The fact that it is a REQUIRED yaml comment is counter intuitive and could
benefit from a clearer note on this fact.
