### ISSUE TITLE
Mounting Storage EXT4 update

### ISSUE THREAD

**Issue by scatterbrain** [coreos/docs#464]
Mounting storage (https://coreos.com/docs/cluster-management/setup/mounting-storage/) documentation has not been updated to reflect that EXT4 is now the default filesystem. 

Especially the "Use Attached Storage for Docker" should be updated to show what the correct parameters when creating EXT4 filesystem should be. I believe the coreos root volume uses non-default inode values, for example.

I would love to send a pull request myself but I'm not quite sure what the parameters to `/usr/sbin/mkfs.ext4` should be and if there are some other issues you should take into account.

**Comment by joshix** [comment]
Closed by #706
