### ISSUE TITLE
mount block storage in openstack

### ISSUE THREAD

**Issue by duffqiu** [coreos/docs#500]
I want to mount a block storage in openstack.
but i have to format(mkfs) before to mount.
the problem is the systemd unit can't support any pre-mount,
how can i format the device before i mount only once?
bceause i want to keep the data in block service after the vm stop / crash

**Comment by duffqiu** [comment]
Currently, my workaround solution is to create a service for this mount, and this service to run the below script:

TYPE=$(blkid /dev/vdc -o value |grep "ext4")

if [[ -z $TYPE ]] ;then
  echo "the block is not formatted, will be formatted by type ext4"
  mkfs.ext4 /dev/vdc
  mkdir /mirror2
fi

**Comment by robszumski** [comment]
You can use systemd's dependency chain, [as documented here](https://coreos.com/docs/cluster-management/setup/mounting-storage/#use-attached-storage-for-docker), to format before mounting.

**Comment by duffqiu** [comment]
the question is if I do like that I will lose the date after reboot the VM, right?
My request is to only format the block storage if it is not formatted at the first time.

I found another workaround solution,
I make an ext4 image (empty)  and upload to openstack, and then use the device-mapping to create/mount a directory with this image when boot a VM. 
this can ignore the formatting step because this image is ext4 already.

**Comment by philips** [comment]
I think we have this documented now: https://coreos.com/os/docs/latest/mounting-storage.html
