### ISSUE TITLE
link to updateservicectl

### ISSUE THREAD

**Issue by philips** [coreos/docs#506]
Getting started with CoreUpdate doesn't link to the updateservicectl binaries: https://github.com/coreos/updateservicectl/releases

@robszumski can you help fix this really quick?

**Comment by philips** [comment]
https://coreos.com/docs/coreupdate/coreos/coreupdate-getting-started/

**Comment by robszumski** [comment]
https://github.com/coreos/updateservicectl/commit/d957967d212df8c814323e9a672669cbc13f73de
