### ISSUE TITLE
Launching CloudFormation stack in EC2 broken

### ISSUE THREAD

**Issue by grepory** [coreos/docs#516]
I'm not entirely sure where to file this issue, but I'm getting an error when I try to launch a stack in EC2.

Clicking on "Launch Stack" and then clicking "Next" yields the following error:

![image](https://cloud.githubusercontent.com/assets/356446/8293026/c23211f4-18e7-11e5-9721-078f020c6e95.png)

Should this be served as JSON instead of gzipped text? The gunzipped version passes JSON linting just fine, so I can only assume that AWS isn't receiving the gunzipped version (i.e. if there's cloudfront or something in front of this S3 bucket, it is serving the gzipped version and not the plaintext version).

**Comment by robszumski** [comment]
@crawford I think your gzip stuff is breaking this

**Comment by crawford** [comment]
Nice, so AWS is ignoring the MIME-type. I'll uncompress those files.

**Comment by grepory** [comment]
Did you try changing the content-type to application/javascript?  It's coming back as binary/octet-stream:

```
λ curl -I https://s3.amazonaws.com/coreos.com/dist/aws/coreos-stable-pv.template
HTTP/1.1 200 OK
x-amz-id-2: VJyYft1IwK2Jf/Qy1k5FZZHFFLpRDPwTdJKmm9NSB0d7pozceB91wzqd6FXR9kAe
x-amz-request-id: A575E31F3524596B
Date: Tue, 23 Jun 2015 01:26:19 GMT
Content-Encoding: gzip
Cache-Control: public, max-age=1800
Last-Modified: Mon, 22 Jun 2015 17:20:45 GMT
ETag: "69bbd9b1de70f723074a67a8109660f5"
Accept-Ranges: bytes
Content-Type: binary/octet-stream
Content-Length: 1369
Server: AmazonS3
```

**Comment by crawford** [comment]
OK, this should be fixed now. @grepory thank you for reporting the bug!

**Comment by grepory** [comment]
No, no! Thank you!
