### ISSUE TITLE
systemd-networkd debugging guide

### ISSUE THREAD

**Issue by philips** [coreos/docs#519]
Essentially the starting place is to enable systemd-networkd debugging levels:

```
mkdir /etc/systemd/system/systemd-networkd.service.d/
echo -e "[Service]\nEnvironment=SYSTEMD_LOG_LEVEL=debug" > /etc/systemd/system/systemd-networkd.service.d/10-debug.conf 
systemctl daemon-reload
systemctl restart systemd-networkd
journalctl -u systemd-networkd
```

@mischief Can you write this up?

**Comment by kayrus** [comment]
we can close this issue

**Comment by philips** [comment]
The guide is posted here: https://coreos.com/os/docs/latest/network-config-with-networkd.html#debugging-networkd
