### ISSUE TITLE
add a guide to swap

### ISSUE THREAD

**Issue by philips** [coreos/docs#52]
Here is a starting point. It would be great to make a utility that handled it a bit better.
## Setup a swap file in the stateful partition

Run these commands as root to create a 512 megabyte swap.

```
fallocate -l 512m /media/state/512MiB.swap
chmod 600 /media/state/512MiB.swap
mkswap /media/state/512MiB.swap
```
## Create a unit to initialize it on boot

Create a unit file at `/media/state/units/swapon.service` with these contents:

```
[Unit]
Description=Turn on swap

[Service]
Type=oneshot
ExecStart=/sbin/swapon /media/state/512MiB.swap

[Install]
WantedBy=local.target
```
## Enable the unit and start using swap

```
systemctl enable --runtime /media/state/units/swapon.service
systemctl start swapon
```

On your next reboot the swap will be turned on automatically.

**Comment by joshperry** [comment]
Why not support the canonical swap configuration? http://cloudinit.readthedocs.org/en/latest/topics/examples.html#adjust-mount-points-mounted

Using this: https://gist.github.com/tsertkov/573d077012ae76443cbf but 50 lines of config just for a swapfile seems excessive.

**Comment by crawford** [comment]
Related https://github.com/coreos/bugs/issues/429#issuecomment-153979506.

**Comment by joelchen** [comment]
Is minimum of round(sqrt(RAM)) and maximum of twice the amount of RAM from https://help.ubuntu.com/community/SwapFaq something we should follow on CoreOS?

**Comment by crawford** [comment]
@joelchen most CoreOS instances don't use swap at all, so the minimum is zero. Canonical's recommended upper bound seems reasonable.

**Comment by joelchen** [comment]
@crawford What are the recommended use cases for no swap, as well as for using swap in CoreOS?

**Comment by crawford** [comment]
@joelchen it depends heavily on how you plan on using the machine and the physical characteristics of the machine. I would suggest taking a look at what Linux recommends and then going with that.

**Comment by HaleTom** [comment]
Do **not** try what @coderfi suggested, namely, disabling CoW to try to use a swapfile with btrfs, until you read that it is supported in the [official documentation](https://btrfs.wiki.kernel.org/index.php/FAQ#Does_btrfs_support_swap_files.3F).

> swap file support relies on one function that btrfs intentionally does not implement due to potential corruptions.

However:
> A workaround, albeit with poor performance, is to mount a swap file via a loop device.

**Comment by philips** [comment]
Someone just mentioned losteup leads to lockups https://groups.google.com/d/msg/coreos-user/xw4aeC68k6Q/vy8Iv0jWCAAJ. Can someone please write this guide? It is clearly tripping up a lot of users on something very simple. cc @ElijahCaine

**Comment by ElijahCaine** [comment]
@philips I'm writing and testing a doc now. PR should be up by the end of the day.
