### ISSUE TITLE
Remove all references of "etcd.service" in favour of "etcd2.service".

### ISSUE THREAD

**Issue by Dynom** [coreos/docs#528]
Referencing `etcd.service` in an Etcd2 cluster kan take down machines in the cluster, depending on the scheduling dependencies. There are still a lot of online resources that reference `etcd.service`, which will result in problems for whomever starts experimenting with Etcd2. As mentioned here: https://github.com/coreos/etcd/issues/3103

There are several pages in the documentation that still reference `etcd.service` where `etcd2.service` would be much favourable.

An overview with outdated documentation: https://www.google.nl/search?q=site%3Acoreos.com+%22name:%20etcd.service%22

**Comment by kayrus** [comment]
Done within https://github.com/coreos/docs/pull/524

**Comment by businessBoris** [comment]
A few of us are using the etcd[v1] from CoreOS v522 relating to this issue: https://github.com/coreos/bugs/issues/319 . I've only just started, but can you keep the outdated docs about for a while please.

**Comment by robszumski** [comment]
@businessBoris The etcd 0.4.x cloud-config parameters are still documented in the cloud-config docs, we're just moving all of the default examples to 2.0.

**Comment by businessBoris** [comment]
@robszumski Thank you. Skittish CoreOS newbie here!

**Comment by robszumski** [comment]
These changes are live at https://coreos.com/os/docs/latest/
