### ISSUE TITLE
cloud-config uses etcd still

### ISSUE THREAD

**Issue by yichengq** [coreos/docs#532]
One user reported that he saw two version of cloud config, one in cloud config section and another in launching a test cluster in https://coreos.com/os/docs/latest/booting-on-ec2.html. The etcd cloud-config should be updated.

**Comment by robszumski** [comment]
This just landed in https://github.com/coreos/docs/pull/524 and will be online shortly

**Comment by yichengq** [comment]
cool.

**Comment by robszumski** [comment]
Live.
