### ISSUE TITLE
Broken Link  in `etcd -> getting-started-with-etcd`

### ISSUE THREAD

**Issue by tdeheurles** [coreos/docs#538]
Just to report a broken link. It seems it is not in the master branch anymore.

In this page :
https://github.com/coreos/docs/blob/master/etcd/getting-started-with-etcd.md

This link do not work anymore :
https://github.com/coreos/docs/blob/master/distributed-configuration/getting-started-with-etcd/index.md

The `distributed-configuration` folder have been removed.

**Comment by robszumski** [comment]
Fixed this page up. Links breaking was some fallout from a reorg. we did, but it should be good to go now.
