### ISSUE TITLE
Naming of deploy_coreos_cluster.sh (deploy_coreos_libvirt.sh)

### ISSUE THREAD

**Issue by Jim-Holmstroem** [coreos/docs#540]
In https://github.com/coreos/docs/blob/master/os/booting-with-libvirt.md

wget https://raw.githubusercontent.com/coreos/docs/master/os/ deploy_coreos_**libvirt**.sh
chmod +x deploy_coreos_**cluster**.sh

There is a few ways this can be solved maintaining backwards compatibility so I didn't want to make a PR for it.

**Comment by robszumski** [comment]
Whoops, I broke this the other day. The reason for the name change is to differentiate this file from what could possibly be another script for a different platform.
