### ISSUE TITLE
Broken link : docs -> fleet -> launching-containers-fleet.md

### ISSUE THREAD

**Issue by tdeheurles** [coreos/docs#541]
Just to signal a broken link (from reorg certainly)
it's [here](https://github.com/coreos/docs/blob/master/fleet/launching-containers-fleet.md).

this link (https://github.com/coreos/docs/blob/master/launching-containers/building/launching-containers-fleet/index.md) on the head of the page.

**Comment by robszumski** [comment]
This frontmatter should have been removed as part of a reorg we just did. Thanks for reporting this!

**Comment by tdeheurles** [comment]
No problem
