### ISSUE TITLE
How to tell fleet to manage Units in cloud-config / fleet path to store Units ?

### ISSUE THREAD

**Issue by tdeheurles** [coreos/docs#542]
I'm trying the [launching containers with fleet guide](https://coreos.com/fleet/docs/latest/launching-containers-fleet.html). 

I have added this to my cloud-config in the coreos.units section :
```yaml
  - name: hello.service
    command: start
    content: |
      [Unit]
      Description=MyApp
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker kill busybox1
      ExecStartPre=-/usr/bin/docker rm busybox1
      ExecStartPre=/usr/bin/docker pull busybox
      ExecStart=/usr/bin/docker run --name busybox1 busybox /bin/sh -c "while true; do echo Hello World; sleep 1; done"
      ExecStop=/usr/bin/docker stop busybox1
```

- docker ps shows that the containers starts
- systemctl status report ok for the units

but fleetctl says it doesn't know that unit :

```bash
core@core ~ $ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
eb37786711ca        busybox            /bin/sh -c while t     37 seconds ago      Up 37 seconds                           busybox1            

core@core ~ $ fleetctl list-units
UNIT	MACHINE	ACTIVE	SUB

core@core ~ $ fleetctl list-unit-files
UNIT	HASH	DSTATE	STATE	TARGET
```

The unit file is created in `/etc/systemd/system/hello.service`

```bash
core@core ~ $ sudo systemctl stop hello

core@core ~ $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

core@core ~ $ fleetctl start hello
Error creating units: unable to find Unit(hello.service) in Registry or on filesystem
```

So I try with the path to the service file :
```bash
core@core ~ $ fleetctl start /etc/systemd/system/hello.service 
Unit hello.service launched on ddbd5481.../10.0.2.15

core@core ~ $ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
8c444fe3655f        busybox             "/bin/sh -c 'while t   40 seconds ago      Up 39 seconds                           busybox1            

core@core ~ $ fleetctl list-unit-files
UNIT		HASH	DSTATE		STATE		TARGET
hello.service	391d247	launched	launched	ddbd5481.../10.0.2.15

core@core ~ $ fleetctl list-units     
UNIT		MACHINE			ACTIVE	SUB
hello.service	ddbd5481.../10.0.2.15	active	running
```

It seems that `/etc/systemd/sytem` is not the good path and writing unit files in cloud-config session can't make fleet manage this units.

For now, I can't find the how to in the documentation

**Comment by jakedt** [comment]
The misunderstanding here is that you're putting your fleet units (which follow `systemd` syntax, and may use systemd as an implementation detail) in the area that is under management of `systemd` itself. `systemd` then sees these units and dutifully starts them when the machine boots.

What you probably want to do us write them out as a file somewhere outside of `systemd`'s purview, i.e. https://coreos.com/os/docs/latest/cloud-config.html#write_files

Use a path which is somewhere else on the filesystem, *not* `/etc/systemd/system`. Then, loading them into fleet becomes the way that you tell fleet about the unit files. These files don't have to be on the machine at all when it boots up! In fact, you don't even have to run `fleetctl` or load the units from a host that's part of your cluster:
https://coreos.com/fleet/docs/latest/using-the-client.html#from-an-external-host
