### ISSUE TITLE
https://coreos.com/fleet/docs/latest/launching-containers-fleet.html

### ISSUE THREAD

**Issue by leafmulch** [coreos/docs#550]
https://coreos.com/fleet/docs/latest/launching-containers-fleet.html
The high availability section regarding launching apache@1.service with docker does not work with docker 1.71 - The -rm flag passed to docker causes an error.
core@core-01 ~ $ fleetctl journal apache@1.service
-- Logs begin at Wed 2015-07-29 15:46:17 UTC, end at Wed 2015-07-29 16:33:57 UTC. --
Jul 29 16:01:18 core-01 docker[1240]: Status: Downloaded newer image for coreos/apache:latest
Jul 29 16:01:18 core-01 systemd[1]: Started My Apache Frontend.
Jul 29 16:01:19 core-01 docker[1305]: flag provided but not defined: -rm
Jul 29 16:01:19 core-01 docker[1305]: See '/usr/bin/docker run --help'.
Jul 29 16:01:19 core-01 systemd[1]: apache@1.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 29 16:01:19 core-01 docker[1313]: Error response from daemon: no such id: apache1
Jul 29 16:01:19 core-01 docker[1313]: Error: failed to stop containers: [apache1]
Jul 29 16:01:19 core-01 systemd[1]: apache@1.service: Control process exited, code=exited status=1
Jul 29 16:01:19 core-01 systemd[1]: apache@1.service: Unit entered failed state.
Jul 29 16:01:19 core-01 systemd[1]: apache@1.service: Failed with result 'exit-code'.

**Comment by robszumski** [comment]
Fixed in https://github.com/coreos/docs/commit/01620f264aac5a085913b70dbbbfcf99695e30ce, thanks!
