### ISSUE TITLE
Cluster architecture needs to use IP variables

### ISSUE THREAD

**Issue by jdloft** [coreos/docs#557]
In `os/cluster-architectures.md` the cloud-configs are hardcoded with IPs they should instead use the private or public IP variables.

**Comment by robszumski** [comment]
Not all platforms support these variables (but most do), which is why they aren't used.

Can you think of a better arrangement we can use to support both use-cases?

**Comment by jdloft** [comment]
We could add a note that the IP 10.0.0.101 should be replaced with the
correct IP.

**Comment by robszumski** [comment]
Fixed in https://github.com/coreos/docs/commit/bd7f3d3e1fd0cdd3573f593a29a1c206d8e0304f. Let me know if you can think of any other improvements we can make.
