### ISSUE TITLE
Sort the tags in the documentation version selector using semver

### ISSUE THREAD

**Issue by jakedt** [coreos/docs#568]
We also probably need to symlink 2.1.0 to latest and tell google/other robots to only index latest. The top result for my etcd 2.X search was 0.4.6.

**Comment by robszumski** [comment]
This is an obvious one but unfortunately this is quite hard in Jekyll which is why it hasn't been done yet :/

Instead of blocking an index, I'd rather figure out how to rank the docs via the sitemap that is submitted to google. Just need to find some time to do that...

**Comment by robszumski** [comment]
This is live.
