### ISSUE TITLE
etcd security model page has a link that returns 404

### ISSUE THREAD

**Issue by dgonyeo** [coreos/docs#662]
On this page:
https://coreos.com/etcd/docs/latest/security.html

3rd paragraph in, "and we provide a full example using the tool at here". The link "here" 404s when viewed on coreos.com. The link is functional when viewed on github.

**Comment by robszumski** [comment]
We need to make sure all links to documentation outside the Documentation folder are absolute, not relative.

Overall, we need to stop putting docs outside of the main location. They aren't discoverable or easy to sync to other locations.
