### ISSUE TITLE
Google seems to prioritize 0.4.7 docs over latest

### ISSUE THREAD

**Issue by sjpotter** [coreos/docs#698]
If one does searches like 

- etcd tls

or 

-etcd api

the top links on google are 0.4.7 documents, we probably want to figure out how to get google to prioritize the latest documents.

ex:

![etcd-tls](https://cloud.githubusercontent.com/assets/1659735/11826858/aeb3fe64-a33c-11e5-9d99-0f4c4e79a981.png)

**Comment by robszumski** [comment]
This is hard because we obviously don't control the page rank algo. I have no idea why some of those pages rank higher than others. We should put a notice on the older pages informing folks that new versions are available.

**Comment by sjpotter** [comment]
I was wondering if we ever linked to the 0.4.7 versioned docs?  Also, if we always link the latest version from older docs that should up its page rank.

**Comment by jonboulle** [comment]
FWIW we have the same issue with some rkt docs - in that case Google seems to have a preference for 0.5.4 for some reason.

**Comment by kevinsimper** [comment]
@robszumski A mention like ClusterHQ and Kubernetes does would be great!

**Comment by robszumski** [comment]
Found some time to figure out why our Google Webmaster Tools account wasn't working properly. These pages are being demoted:

 - https://coreos.com/rkt/docs/0.5.4/*
 - https://coreos.com/etcd/docs/0.4.7/*

**Comment by robszumski** [comment]
Will check back to see if the rankings change over the next week or two. Closing for now.
