### ISSUE TITLE
Insecure private networking with DigitalOcean

### ISSUE THREAD

**Issue by kevinsimper** [coreos/docs#718]
I am looking at the tutorial for setting up CoreOS on digitalOcean, and the default is to listen on the private_ip. The problem is that private networking on digitalocean is shared.

Wouldn't that mean that everybody inside the private networking on digitalocean would be able to join my coreos cluster?

**Comment by robszumski** [comment]
You can use TLS with etcd to keep your peer traffic secure: https://coreos.com/etcd/docs/latest/security.html#example-3-transport-security-&-client-certificates-in-a-cluster

The examples on that guide are etcd command line flags, but the same parameters map directly to env vars as well.

**Comment by kevinsimper** [comment]
Yes, but a beginner might not know that and I was thinking that the docs should say, "not secure, you can be hacked"!

**Comment by robszumski** [comment]
It's hard to balance ease of use, consistency with the way other platforms are bootstrapped, and working around the inferior practices of some of the providers.

Would be happy to a look at a PR if you want to put a suggestion together.
