### ISSUE TITLE
Embrace and extinguish older style guide

### ISSUE THREAD

**Issue by joshix** [coreos/docs#735]
https://gist.github.com/brianredbeard/3ef1e0df9f580d002000

**Comment by ElijahCaine** [comment]
@joshix Should we integrate this with STYLE.md?

**Comment by joshix** [comment]
Closed complete, have incorporated or material aged out of date.

@ElijahCaine Please check with UX to discover the location of current color and typeface guide, which doesn't belong in the docs STYLE doc but should be known.
