### ISSUE TITLE
Improve the documentation of "Running rkt with an LKVM stage1"

### ISSUE THREAD

**Issue by jusle** [coreos/docs#746]
The page [Running rkt with an LKVM stage1](http://j.mp/1PZrnAQ) starts with the following sentence:

> rkt has experimental support for running with an LKVM stage1.

At CoreOS IRC channel I asked what "experimental support" exactly means. [Here](http://j.mp/20PDybp) is the full discussion.

I hope the documentation of rkt 1.0 with LKVM would be improved. Especially the status of the support by CoreOS needs clarification.

**Comment by philips** [comment]
We should probably mirror this issue into the rkt repo, right @joshix? Or are you working on this?


cc @alban @jonboulle @iaguis

**Comment by alban** [comment]
@philips ok, mirrored on https://github.com/coreos/rkt/issues/2163

**Comment by joshix** [comment]
@philips: Yeah I was working on it: https://github.com/coreos/rkt/issues/2169

**Comment by jusle** [comment]
Thank you all. I have an idea: webcast with demo to run the related best practices setup we [talked about on Twitter](https://twitter.com/JussiLehto/status/696657057466834945)? The diagram will be updated, and I'll be in touch in the next few days after some testing for production workloads. @philips & co
