### ISSUE TITLE
Launching on EC2 layout is broken at Manual setup :: Launching a test cluster

### ISSUE THREAD

**Issue by groner** [coreos/docs#753]
The instructions appear to end here.

<img width="456" alt="screen shot 2016-02-17 at 11 24 34 am" src="https://cloud.githubusercontent.com/assets/47317/13116271/44c55494-d569-11e5-89a1-2c9e82c72818.png">

---

The remaining instructions are in the Alpha Channel tab.

<img width="446" alt="screen shot 2016-02-17 at 11 28 39 am" src="https://cloud.githubusercontent.com/assets/47317/13116400/df38b8ae-d569-11e5-8933-b5a8cbff2ef9.png">

---

It looks like the `<pre>` blocks aren't being closed?

<img width="459" alt="screen shot 2016-02-17 at 11 29 09 am" src="https://cloud.githubusercontent.com/assets/47317/13116444/fec15f46-d569-11e5-89a8-9c59bf2c0572.png">
<img width="472" alt="screen shot 2016-02-17 at 11 29 48 am" src="https://cloud.githubusercontent.com/assets/47317/13116447/01826874-d56a-11e5-87ae-bb1bc34a7390.png">

**Comment by robszumski** [comment]
Should be fixed by https://github.com/coreos/docs/pull/754, thanks for reporting!

**Comment by robszumski** [comment]
Should be live shortly.

**Comment by groner** [comment]
That was fast!
