### ISSUE TITLE
libvirt: add possibility to verify image signature

### ISSUE THREAD

**Issue by kayrus** [coreos/docs#760]
relates to https://github.com/coreos/docs/issues/583
/cc @mischief I have this in my TODO list for a long time :)

**Comment by kayrus** [comment]
`gpg --enable-special-filenames --verify <(curl -s http://stable.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2.sig) <(curl http://stable.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2 | tee >(bzcat > coreos_production_qemu_image.img))`

**Comment by kayrus** [comment]
relates to https://github.com/coreos/docs/issues/736

**Comment by kayrus** [comment]
https://coreos.com/os/docs/latest/verify-images.html

**Comment by euank** [comment]
Our libvirt docs now recommend doing a `gpg --verify` in the download section (part of #1119).
