### ISSUE TITLE
Add an info on how to boot CoreOS using EFI boot inside QEMU VM

### ISSUE THREAD

**Issue by kayrus** [coreos/docs#761]
Download and unpack OVMF x86_64 image - https://sourceforge.net/projects/edk2/files/OVMF/

patch `coreos_production_qemu.sh`:

``` diff
VM_PFLASH_RW=ovmf.fd
VM_PFLASH_RO=ovmf_ro.fd
```

Run script, then inside VM's EFI shell type:

```
fs0:
EFI\boot\bootx64.efi
```

Enjoy EFI boot

**Comment by ElijahCaine** [comment]
@kayrus Is this still relevant? If so can you elaborate on what needs to happen here?

**Comment by kayrus** [comment]
it is necessary mostly for coreos developers (i.e. @mjg59 ). don't think regular user will need this info

**Comment by ElijahCaine** [comment]
@kayrus In that case I will close this. If it comes up again we can re-open it and discuss implementation.
