### ISSUE TITLE
Add xhyve as a community-supported platform

### ISSUE THREAD

**Issue by robszumski** [coreos/docs#765]
Convert the barebones instructions from https://github.com/coreos/coreos-xhyve#download-and-run-coreos into a proper guide.

I'm thinking that the [libvirt](https://github.com/coreos/docs/blob/master/os/booting-with-libvirt.md) guide might serve as a good base.

**Comment by jgmize** [comment]
Might want to link to https://github.com/TheNewNormal/coreos-osx as well.

**Comment by robszumski** [comment]
@jgmize Are you interested in giving this a shot?

**Comment by jgmize** [comment]
> @jgmize Are you interested in giving this a shot?

Thanks @robszumski, but there are other docs I need to write first, and I can't commit to assembling a proper guide for CoreOS on xhyve in the near (or even medium) term.

**Comment by ElijahCaine** [comment]
In an effort to triage the docs issues this is being closed due to inactivity.
If it's still relevant feel free to re-open.
