### ISSUE TITLE
Bare-metal install w/o video

### ISSUE THREAD

**Issue by iDiogenes** [coreos/docs#769]
I am looking to install coreos on a system that does not have a video output. Just a few NIC's, a USB port and a serial console. When the system boots the output is fine until the kernel loads and then  all text disappears. I tried changing the baudrate to all the common ones and then some, but still nothing. The system is booting from a USB ISO image, not PIX. 

Also, the system does end up with an IP address so if the core user happens to have a default password I would be able to SSH to do the install. However, I believe I read that there was no default password, so SSH would not be possible.

Any help would be appreciated.  Thanks!

**Comment by iDiogenes** [comment]
Please disregard or feel free to delete. I was able to use the install script with the cloud-config.yml to install a bootable version to the USB drive.

**Comment by joshix** [comment]
Closing on behalf of reporter. Resolved.

**Comment by naisanza** [comment]
@iDiogenes where do you put the cloud-config.yml? Do you have to put it in the ISO?
