### ISSUE TITLE
Adding Link to a book - CoreOS in Action (Manning Publications)

### ISSUE THREAD

**Issue by Aleks-d** [coreos/docs#782]
Hello, 

This is Aleks with Manning Publications. We publish computer books for professionals – programmers, system administrators, designers, system architects, managers and others. We are currently developing a book - [CoreOS in Action](https://www.manning.com/books/coreos-in-action) by Matt Bailey. This book will help readers discover end-to-end deployment of CoreOS in Amazon Web Services, and learn from real-world examples of application stacks.

I wanted to contact you and see if you'd be interested in adding the link to the book to the CoreOS documentation/resources page. We believe it will offer significant support to the users and the CoreOS community and that it represents valuable resource.

I can provide you with cover graphics/copy and everything else you may need. 

Let me know what do you think.

Kind regards,
Aleks
aldr@manning.com

**Comment by robszumski** [comment]
Endorsing one publication over another isn't something we're prepared to do at this time. The book looks great and I wish you a ton of success with it!
