### ISSUE TITLE
booting with PXE docs reference "above" and it doesn't exist

### ISSUE THREAD

**Issue by philips** [coreos/docs#793]
"root: Use a local filesystem for root instead of one of two in-ram options above"

I don't see anything above on this page: https://coreos.com/os/docs/latest/booting-with-pxe.html

**Comment by marineam** [comment]
ah, doc for rootfstype got removed at some point. No root= option will default to tmpfs

**Comment by philips** [comment]
@marineam how should it read? Can you help fix it up?

**Comment by philips** [comment]
@robszumski @joshix This has to be added to the iPXE docs as well! https://github.com/coreos/docs/blob/master/os/booting-with-ipxe.md

**Comment by joshix** [comment]
Closed fixed by #796 and #799
