### ISSUE TITLE
checker for coreos.com docs links

### ISSUE THREAD

**Issue by kayrus** [coreos/docs#832]
Create a tools which checks whether links are valid.

I.e. this doc https://coreos.com/etcd/docs/latest/etcd-live-http-to-https-migration.html has a link to https://coreos.com/etcd/docs/os/generate-self-signed-certificates.html which actually should link to this doc: https://coreos.com/os/docs/latest/generate-self-signed-certificates.html

**Comment by crawford** [comment]
https://crates.io/crates/marker
