### ISSUE TITLE
Locksmithd reboot window & locksmithd.service restart

### ISSUE THREAD

**Issue by sepiroth887** [coreos/docs#842]
Hi, 

We are using locksmithd with a reboot window and update strategy best-effort/none. I'm wondering if locksmith will be able to recover the intent to reboot after the unit is restarted? I found nothing in the code to suggest it would but then again i'm not too familiar with dbus messaging. 

If it's not able to recover is this something worth supporting in the future?

**Comment by crawford** [comment]
First off, you shouldn't use the "best-effort" strategy anymore. It's been deprecated in favor of an explicit choice between "reboot" and "etcd-lock".

Second, I don't follow your question. Locksmith itself doesn't store any state - it just looks to other daemons to determine what action to take. Can you explain the situation a little bit more?

**Comment by ElijahCaine** [comment]
In an effort to triage the docs this is being closed due to inactivity.
