### ISSUE TITLE
os: out of date azure docs

### ISSUE THREAD

**Issue by kbrwn** [coreos/docs#910]
A customer reported this in a ticket. I believe there has been a major update to the Azure console since our doc was last touched.

**Comment by kbrwn** [comment]
cc @omkensey @joshix

**Comment by crawford** [comment]
I'd also like to update the instructions to use ARM instead of ASM. I think we might just be able to throw a button on the page that launches an instance.

**Comment by omkensey** [comment]
Is this referring to https://coreos.com/os/docs/latest/booting-on-azure.html or some other page?

**Comment by crawford** [comment]
That is the page to which I'm referring. I assume that is true for @kbrwn as well.

**Comment by brianredbeard** [comment]
There is not a specific page that the customer was referring to.

**Comment by crawford** [comment]
Related to https://github.com/coreos/docs/issues/694.

**Comment by bgilbert** [comment]
We now use ARM and the new Azure CLI (`az`).  No launch button, though.

**Comment by crawford** [comment]
I don't think the button is as useful anymore. [This blog](https://azure.microsoft.com/en-us/blog/deploy-to-azure-button-for-azure-websites-2/) details how to implement it if anyone is interested in the future.
