### ISSUE TITLE
Installing modified CoreOS to bare metal machine

### ISSUE THREAD

**Issue by Dm3Ch** [coreos/docs#911]
Hello!
How could I install modified CoreOS image on my bare metal machine.
I got modified image by following instruction (https://coreos.com/os/docs/latest/sdk-modifying-coreos.html).

I can not find any information about this neither in that instruction nor in the coreos-install utility documentation.

**Comment by crawford** [comment]
On 11/03, Dmitry Chepurovskiy wrote:
> How could I install modified CoreOS image on my bare metal machine.
> I got modified image by following instruction (https://coreos.com/os/docs/latest/sdk-modifying-coreos.html).

After you run `./build_image`, there will be a disk image
(coreos_production_image.bin) in the resulting build directory. This can
be dd'd directly to the front of the disk and then booted. The image
will automatically expand to fill the remainder of the disk.

-Alex

**Comment by Dm3Ch** [comment]
Thank you.
I already resolve it. And modified default coreos-install to write custom images.
