### ISSUE TITLE
manual-rollbacks: state you can't downgrade arbitrarily

### ISSUE THREAD

**Issue by ahmetb** [coreos/docs#964]
I was reading this doc https://coreos.com/os/docs/latest/manual-rollbacks.html#performing-a-manual-rollback to find out "how can I downgrade coreos to a lower version I never installed in the same channel (i.e. stable)".

I see others hit the same problem as well and people suggest this article as the solution: https://groups.google.com/forum/#!topic/coreos-user/c8xu5f3nhBw

However it doesn't tell want I exactly needed to hear. I am told the following at https://github.com/coreos/bugs/issues/1747 :

> There is no way to downgrade to an arbitrary version without using CoreUpdate (a commercial product).

Maybe it's just me but the docs don’t make it clear to me (a first-time user) that I can't just install a lower version number.

**Comment by joshix** [comment]
@radhikapc The ideal fix for this will add a note to coreos/docs/os/manual-rollbacks.md to the effect that it is impossible to downgrade Container Linux to an arbitrary older version. Instead, you can rollback to the last good partition after an upgrade, OR change to a lower release channel (and thereby receive the latest release on that channel, not a version arbitrarily selected by the user). 

Those two methods are covered in the existing doc. Simply make it clear that one can't pick a version by number.

**Comment by joshix** [comment]
ref https://www.pivotaltracker.com/story/show/142282025

**Comment by radhikapc** [comment]
Got it @joshix. Thanx

**Comment by zbwright** [comment]
gonna add this note at the top, just before tldr, when we walk through the Git process:

Note: Container Linux allows you to rollback to a previously active partition, or change to an older release channel (to downgrade to a stable version). It does not allow you to downgrade to an  uninstalled, user defined version number.

**Comment by radhikapc** [comment]
user-defined?

**Comment by zbwright** [comment]
This tiny ticket is surfacing a few style guide issues. We'll chat them today in the team meeting.

**Comment by joshix** [comment]
closed fixed in https://github.com/coreos/docs/issues/1034
