### ISSUE TITLE
Error by building custom kernel modules

### ISSUE THREAD

**Issue by rastislavszabo** [coreos/docs#977]
Hi,
I followed this doc:

https://github.com/coreos/docs/blob/05a178bd51ee3c6940f7a6360d56bc660d324a1d/os/kernel-modules.md

and run into this issue:

```
coreos_developer_container ~ # emerge -gKav coreos-sources


!!! Error fetching binhost package info from 'http://builds.developer.core-os.net/boards/amd64-usr/1235.6.0/pkgs/'
!!! HTTP Error 404: Not Found



!!! Error fetching binhost package info from 'http://builds.developer.core-os.net/boards/amd64-usr/1235.6.0/toolchain/'
!!! HTTP Error 404: Not Found


These are the packages that would be merged, in order:

Calculating dependencies |Unable to enable loopback interface: EPERM                                                                                                                       ... done!

emerge: there are no binary packages to satisfy "coreos-sources".

emerge: searching for similar names...
emerge: Maybe you meant any of these: sys-kernel/coreos-modules, coreos-base/coreos-dev, coreos-base/coreos-au-key?

```

**Comment by joshix** [comment]
@rastislavszabo Sorry you've run into this. While the doc is technically correct, there is a [known issue](https://github.com/coreos/bugs/issues/1762) with the dev container right now. I'll let you know more as we get it sorted. 

As [mentioned in the other issue report](https://github.com/coreos/bugs/issues/1762#issuecomment-274175276), you can work around this with existing sources by (temporarily) omitting the `g` and `K` flags from your `emerge` command.

**Comment by rastislavszabo** [comment]
Thanks for the info!
