### ISSUE TITLE
CSS or JS error on website

### ISSUE THREAD

**Issue by elimisteve** [coreos/docs#983]
If I'm near the top of the page, everything looks fine:

## Pic 1

![coreos-rkt-docs-error1-screenshot - 01312017 - 06 01 22 pm](https://cloud.githubusercontent.com/assets/139603/22492628/997a1108-e7df-11e6-9c04-507588375d35.png)

...but if I scroll down a bit, this weird overlay thing happens:

## Pic 2

![coreos-rkt-docs-error2-screenshot - 01312017 - 06 01 43 pm](https://cloud.githubusercontent.com/assets/139603/22492629/997aed6c-e7df-11e6-8d62-a4445001d542.png)

Browser: Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04 (64-bit)

**Comment by elimisteve** [comment]
Note that this is not unique to the rkt docs; here's an example for fleet:

![coreos-rkt-docs-error3-screenshot - 01312017 - 06 01 43 pm](https://cloud.githubusercontent.com/assets/139603/22492731/43c03908-e7e0-11e6-9aa8-9ce3cd616c95.png)

**Comment by elimisteve** [comment]
Figured it out: the CSS meant to make the docs responsive doesn't quite work when the zoom level is 175%, but works fine the rest of the time.

**Comment by robszumski** [comment]
We're about to tweak this layout a bit as well, so that might fix this issue for you. Thanks for reporting.

**Comment by robszumski** [comment]
Verified that this was an issue, and the fix is live. Thanks again!

**Comment by elimisteve** [comment]
Thank _you_!
