### ISSUE TITLE
Ignition specification duplicated

### ISSUE THREAD

**Issue by urzds** [coreos/docs#987]
The [CoreOS Container Linux "configuration" documentation](https://coreos.com/os/docs/latest/configuration.html) seems to be a duplicate of the [CoreOS Ignition specification](https://coreos.com/ignition/docs/latest/configuration.html)

**Comment by crawford** [comment]
Where did you find a link to that? That page shouldn't be there (we'll have to purge that from the backend).

**Comment by urzds** [comment]
https://coreos.com/os/docs/latest -> `Uncategorized Documents`. There is more.

**Comment by crawford** [comment]
Ah, I see it now. That specification is correct. Both the Container Linux and Ignition configs very closely resemble each other today (that's going to change as time goes on). We can at least fix up the title and categorize the document though..........

**Comment by urzds** [comment]
So CL config will be an Ignition config, but understand additional parameters? Like the coreos-cloudconfig was a cloud-config with additional parameters?

**Comment by crawford** [comment]
CL config is a completely separate config from Ignition. It just so happens that it resembles Ignition in structure, but that is purely a temporary implementation detail. It will change over time.

**Comment by bgilbert** [comment]
This looks to have been fixed per https://github.com/coreos/docs/issues/987#issuecomment-277838808.
