### ISSUE TITLE
Kubernetes docs out of order

### ISSUE THREAD

**Issue by urzds** [coreos/docs#988]
I am looking at https://coreos.com/kubernetes/docs/latest/ or the left panel at https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html:
The order there is step 5, 2, 3, 1, 4. Also, the CA creation comes last, while it should probably come before step 1.

**Comment by robszumski** [comment]
I noticed this too, it's on the list to fix. Thanks for reporting.

**Comment by robszumski** [comment]
This fix is live: https://coreos.com/kubernetes/docs/latest/getting-started.html
