### ISSUE TITLE
CoreOS Container Linux etcd setup guide missing?

### ISSUE THREAD

**Issue by urzds** [coreos/docs#989]
I am looking at https://coreos.com/etcd/docs/latest/dl_build.html. In the left navigation panel I cannot find a link to a guide how to setup etcd on CoreOS Container Linux. There are all kinds of guides for running it manually, but there seems to be none explaining e.g. the `etcd-member.service` systemd.unit.

**Comment by philips** [comment]
Yes, we need to fix this ASAP. cc @joshix @coreos/team-os 

The docs are at the bottom of this blog post: https://coreos.com/blog/toward-etcd-v3-in-container-linux.html

```
$ systemctl enable /usr/lib/coreos/etcd-member.service
$ systemctl start etcd-member
$ rkt list
UUID		APP	IMAGE NAME			STATE	CREATED		STARTED		NETWORKS
4d566696	etcd	quay.io/coreos/etcd:v3.0.10	running	6 minutes ago	6 minutes ago
$ etcdctl set fname Regis
$ etcdctl get fname
Regis
```

It needs to be cross linked from the following locations:

- https://coreos.com/etcd/docs/latest/getting-started-with-etcd.html

And needs to replace this doc:

- https://coreos.com/etcd/docs/latest/v2/docker_guide.html

**Comment by joshix** [comment]
fixed (a bit ago) in https://github.com/coreos/docs/commit/37312455f993a8595277aa39d440fabfa2a791d3

expanded in https://github.com/coreos/docs/pull/1016

_published_ in 3.1.3: https://coreos.com/etcd/docs/latest/getting-started-with-etcd.html

**Comment by joshix** [comment]
closed fixed (MVP)
