### ISSUE TITLE
Using environmentfiles

### ISSUE THREAD

**Issue by stuaxo** [coreos/docs#998]
The environmentfiles page doesn't have any examples of what is IN an environmentfile
https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html

Probably just need a few examples, I'm assuming it is KEY=VALUE but, without examples I don't know.

The doc is missing
```$ cat /run/flannel_docker_opts.env```

{whatever that file contains}

Other questions that came out of not knowing the syntax - if I want dynamic values, do I use another script to generate the environment file ?

Can I create a value that will stay the same until the device is next rebooted, some sort of salted hash of /proc/sys/kernel/random/boot_id

?
Can I do this with environment files ?

**Comment by crawford** [comment]
You can use the `%b` [specifier](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers) for that.

**Comment by robszumski** [comment]
Made a quick PR for this. Is this what you were looking for @stuaxo? https://github.com/coreos/docs/pull/999

**Comment by stuaxo** [comment]
Awesome, cheers :)

I think the filename needs to be fleet_machines.env

I realise the syntax is kind of obvious, but I couldn't find many examples on the net.
